spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booksdb?createDatabaseIfNotExist=true&&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: Password@123
  jpa:
    hibernate:      
      ddl-auto: update      
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect   
    
server:
 port: 8081
